# Generated by Django 4.2.1 on 2024-04-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_information',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='eps',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_surgeries',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
