# Generated by Django 4.2.1 on 2024-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_patient_allergies_patient_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='eps',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
