# Generated by Django 4.2.1 on 2024-04-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_remove_patient_eps_patient_birthplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
