# Generated by Django 4.2.1 on 2024-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_remove_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
