# Generated by Django 4.2.1 on 2024-04-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_patient_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
